// import type { Metadata } from "next";
// import { Geist, Geist_Mono } from "next/font/google";
// import "./globals.css";
// import Headers from "./components/Headers";
// // import { AuthProvider } from "@/app/api/auth/[...nextauth]";

// import { Providers } from "./providers";

// const geistSans = Geist({
//   variable: "--font-geist-sans",
//   subsets: ["latin"],
// });

// const geistMono = Geist_Mono({
//   variable: "--font-geist-mono",
//   subsets: ["latin"],
// });

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

// export default function RootLayout({
//   children,
// }: Readonly<{
//   children: React.ReactNode;
// }>) {
//   return (
//     <html lang="en">
     
//       <body
//         className={`${geistSans.variable} ${geistMono.variable} antialiased`}
//       >
// <Providers>

//          {/* <AuthProvider> */}
//          <Headers/>

//         {children}
//          {/* </AuthProvider> */}

//          </Providers>
//       </body>
//     </html>
//   );
// }
import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Headers from "./components/Headers";
import { Providers } from "./providers";
import { AddToCartModal } from "@/app/components/AddToCartModal";
import { CartButton } from "@/app/components/CartButton";
import { SocketProvider } from "./providers/SocketProvider";
import { SessionDebug } from "./components/SessionDebug";
const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "FoodHub - Order Delicious Meals",
  description: "Premium food ordering and delivery service",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <Providers>
          <SocketProvider>

          <Headers />
          {children}
          
          {/* Global Cart Components */}
          <AddToCartModal />
          <CartButton />
          <SessionDebug />
          </SocketProvider>
        </Providers>
      </body>
    </html>
  );
}